# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'de95ff58-29e2-4fc0-832b-24031d36b711'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'


- task: DotNetCoreCLI@2
  displayName: 'Run and publish unit tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--filter TestCategory!~Functional'

- task: DockerCompose@0
  displayName: 'Run functional tests'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'docker-compose-test.yml'
    additionalDockerComposeFiles: 'docker-compose-test.override.yml'
    projectName: '$(Build.Repository.Name).TournamentServiceApiFunctionalTest'
    action: 'Run services'
    detached: false
    requireAdditionalDockerComposeFiles: true

- task: PublishTestResults@2
  displayName: 'Publish functional tests'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/*-test-results.xml'
    failTaskOnFailedTests: true
