version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
  
  mongodb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: Services/IdentityService/IdentityService.API/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb


  simpleapigateway:
    image: ${DOCKER_REGISTRY-}simpleapigateway
    build:
      context: .
      dockerfile: Services/ApiGateway/SimpleApiGateway/Dockerfile
    depends_on:
      - rabbitmq
      - identityservice.api


  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: Services/UserService/UserService.API/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
      - simpleapigateway

  tournamentservice-api:
    image: ${DOCKER_REGISTRY-}tournamentserviceapi
    build:
      context: .
      dockerfile: Services/TournamentService/TournamentService.API/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
      - simpleapigateway
      - userservice.api
