version: "3.4"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "paSSword123"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
    tournament-api:
        build: 
            context: .
            dockerfile: TournamentService.API/Dockerfile
        ports: 
            - "5001:80"
        depends_on: 
            - "db"
            - "rabbitmq"
        # command: sh - c './wait-for-it.sh db:1433 -t 120 -- dotnet TournamentService.API.dll'
        # entrypoint: ["wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "TournamentService.API.dll"]